import {Evento} from './eventTypes';

export const eventListMock: Evento[] = [
  {
    id: '1',
    codigo: 1,
    foto: 'https://img.freepik.com/fotos-premium/voluntariado-em-um-evento-comunitario_670382-32923.jpg?w=2000',
    nome: 'Almoço comunitário',
    visibilidade: 'PUBLICO_GERAL',
    data_hora_inicio: '10/10/2023 12:00',
    data_hora_final: undefined,
    presencial_endereco: 'Praça do Saber 20 A, Centro - São Paulo',
    virtual_link: undefined,
    tematico_descricao: undefined,
    observacoes: 'Venha fazer parte desse lindo gesto de amor ao próximo',
    // usuario: {
    //   id: '1',
    //   nome: 'Leandro Rebouças',
    //   email: 'contato@leandroreboucas.com',
    //   foto: 'https://github.com/leandroreboucas.png',
    //   data_nascimento: '24/08/1989',
    //   ativo: true,
    //   data_cadastro: '04/10/2023 11:02:03',
    //   data_atualizacao: '04/10/2023 11:02:03',
    // },
    // arquivado: false,
    // finalizado: false,
    // data_cadastro: '04/10/2023 11:02:03',
    // data_atualizacao: '04/10/2023 11:02:03',
    participantes: 10,
  },

  {
    id: '2',
    codigo: 2,
    foto: 'https://img.freepik.com/fotos-gratis/medicos-femininos-de-vista-frontal-ajudando-o-paciente_23-2149844605.jpg?size=626&ext=jpg',
    nome: 'Visita ao hospital',
    visibilidade: 'REDE_AMIGOS',
    data_hora_inicio: '15/10/2023 11:00',
    data_hora_final: undefined,
    presencial_endereco: 'Avenida principal, Centro - São Paulo',
    virtual_link: undefined,
    tematico_descricao: undefined,
    observacoes:
      'As visitas ao C.T.I. acontecem somente de segunda-feira a sexta-feira das 11:00h as 12:00 e das 17:00h as 18:00h; e nos finais de semana, das 14:00h as 17:00h.',
    // usuario: {
    //   id: '1',
    //   nome: 'Leandro Rebouças',
    //   email: 'contato@leandroreboucas.com',
    //   foto: 'https://github.com/leandroreboucas.png',
    //   data_nascimento: '24/08/1989',
    //   ativo: true,
    //   data_cadastro: '04/10/2023 11:02:03',
    //   data_atualizacao: '04/10/2023 11:02:03',
    // },
    // arquivado: false,
    // finalizado: false,
    // data_cadastro: '04/10/2023 11:02:03',
    // data_atualizacao: '04/10/2023 11:02:03',
    participantes: 7,
  },
];
